# Generated by Django 3.1.3 on 2023-10-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('Nombre', models.CharField(max_length=50)),
                ('Numero_Colegiado', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('Especialidad', models.CharField(max_length=50)),
                ('Diagnostico', models.CharField(max_length=50)),
                ('Otros', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('Nombre', models.CharField(max_length=50)),
                ('DPI', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('Direccion', models.CharField(max_length=50)),
                ('Fecha_Nacimiento', models.CharField(max_length=50)),
                ('Razon_Visita', models.CharField(max_length=50)),
                ('Numero', models.CharField(max_length=8)),
                ('Otros', models.CharField(max_length=50)),
            ],
        ),
    ]
